### ISSUE TITLE
Release v0.0.16 upload to PyPI failed

### ISSUE THREAD

**Issue by hammerhead** [crate/cratedb-toolkit#222]
Pushing the latest release to PyPI failed due to a dependency issue:

```
Uploading distributions to https://upload.pypi.org/legacy/
Uploading cratedb_toolkit-0.0.16-py3-none-any.whl
WARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Can't have direct dependency: lorrystream@                             
         git+https://github.com/daq-tools/lorrystream.git@55cf456fdcd3 ; extra  
         == "kinesis". See                                                      
         https://packaging.python.org/specifications/core-metadata for more     
         information.    
```

Full log: https://github.com/crate/cratedb-toolkit/actions/runs/10089117641/job/27896022759

**Comment by amotl** [comment]
Hi. That other patch will probably need to converge before being able to run a release. I will try to bring it in as soon as possible.

- https://github.com/daq-tools/lorrystream/pull/120

**Comment by amotl** [comment]
Hi. Version [v0.0.17](https://github.com/crate/cratedb-toolkit/releases/tag/v0.0.17) has been released, so I guess it is safe to close this issue. Thanks again.
