### ISSUE TITLE
[I/O] Investigate single-record inserts on bulk interface

### ISSUE THREAD

**Issue by amotl** [crate/cratedb-toolkit#310]
## Introduction
On another spot, CTK's test suite discovered a regression in CrateDB, that made those test cases trip.
```
FAILED tests/adapter/test_rockset.py::test_rockset_add_documents - crate.client.exceptions.ProgrammingError: IndexOutOfBoundsException[Index: 1, Size: 1]
FAILED tests/adapter/test_rockset.py::test_rockset_query - crate.client.exceptions.ProgrammingError: IndexOutOfBoundsException[Index: 1, Size: 1]
FAILED tests/io/test_import.py::test_import_csv_dask - crate.client.exceptions.ProgrammingError: IndexOutOfBoundsException[Index: 1, Size: 1]
FAILED tests/io/test_import.py::test_import_csv_dask_with_progressbar - crate.client.exceptions.ProgrammingError: IndexOutOfBoundsException[Index: 1, Size: 1]
```

- https://github.com/crate/crate/issues/16916

## Thoughts
Depending on number of ingress records, and chunk size, it can always happen that there are single records being submitted to the bulk interface. However, we should take the chance to validate that those are actually just stray records, and that it does not happen across the boar, because performance would be poor.

**Comment by seut** [comment]
Should be fixed by https://github.com/crate/crate/pull/16921.
